[package]
name = "rustycast"
version = "0.0.1"
authors = [
	"Jeremy Burns <j@jaburns.net>",
]

[[bin]]
name = "rustycast"
path = "src/main.rs"

[dependencies.sdl2]
path = "lib/rust-sdl2"

[dependencies]
rand = "0.1.3"
time = "0.1.20"
