[package]
name = "rustycast"
version = "0.0.1"
authors = [
	"Jeremy Burns <j@jaburns.net>",
]

[[bin]]
name = "rustycast"
path = "src/main.rs"

[dependencies.sdl]
path = "lib/rust-sdl"

[dependencies.sdl_image]
path = "lib/rust-sdl/src/sdl_image"

[dependencies]
rand = "0.1.3"
time = "0.1.20"
