[package]
name = "rustycast"
version = "0.0.1"
authors = [
	"Jeremy Burns <j@jaburns.net>",
]

[[bin]]
name = "rustycast"
path = "src/main.rs"

[dependencies]
sdl2 = "*"
time = "*"

[dependencies.sdl2_image]
path = "lib/rust-sdl2_image"
