[package]
name = "rustycast"
version = "0.0.1"
authors = [
	"Jeremy Burns <j@jaburns.net>",
]

[[bin]]
name = "rustycast"
path = "src/main.rs"

[dependencies]
sdl2 = "*"
sdl2-sys = "*"
time = "*"

[dependencies.sdl2_image]
git = "https://github.com/jaburns/rust-sdl2_image"
