[package]
name = "rustycast"
version = "0.0.1"
authors = [
	"Jeremy Burns <j@jaburns.net>",
]

[[bin]]
name = "rustycast"
path = "main_basic.rs"

[dependencies.sdl]
path = "/Users/jaburns/sources/rust-sdl"
